# Generated by Django 5.0 on 2024-01-05 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
        ('estabelecimento', '0004_remove_estabalecimento_agendamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='estabelecimento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='estabelecimento.estabalecimento'),
            preserve_default=False,
        ),
    ]
