# Generated by Django 5.0 on 2024-01-05 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0002_agendamento_estabelecimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='codigo_estabelecimento',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='nome_estabelecimento',
        ),
    ]
