# Generated by Django 5.0 on 2024-01-04 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estabalecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=8)),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamento.agendamento')),
            ],
        ),
    ]
