# Generated by Django 5.0 on 2024-01-04 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
        ('estabelecimento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estabalecimento',
            name='agendamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agendamento.agendamento'),
        ),
    ]
