# Generated by Django 5.0 on 2024-01-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimento', '0002_alter_estabalecimento_agendamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estabalecimento',
            name='codigo',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
