# Generated by Django 5.0 on 2024-01-05 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimento', '0003_alter_estabalecimento_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estabalecimento',
            name='agendamento',
        ),
    ]
